In [9]:
import numpy as np

In [10]:
# Creating NumPy Arrays - from lists
arr = np.array([1, 2, 3, 4])
print(arr, type(arr))

arr2 = np.array([1, 2, 3, 4, "prime"])
print(arr2, type(arr2))

# 2D Arrays - Matrix
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3, arr3.shape)

[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] (2, 3)


In [17]:
# Creating NumPy Arrays - from scratch
arr1 = np.zeros((3, 4)) #pre-filled with 0's
print(arr1, arr1.shape)

arr = np.ones((4,4))#pre-filled with 1's
print(arr,arr.shape)

arr3 = np.full((2, 3), 5) #pre-filled with a num
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4)

arr5 = np.arange(1, 20, 2) #elements in range
print(arr5)

arr6 = np.linspace(0, 10, 5) #evenly spaced array
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (4, 4)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.   2.5  5.   7.5 10. ]


In [26]:
# Array Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(arr.shape) #dimensions - (m x n)
print(arr.size) #total elements - m*n
print(arr.ndim) #dimension
print(arr.dtype) #data type object

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

str_arr = np.array([1, 2, 3], dtype="U")
print(str_arr, str_arr.dtype)

(4, 3)
12
2
int32
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] float64
['1' '2' '3'] <U1


In [32]:
# Reshaping
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr,arr.shape)

reshaped = arr.reshape((4,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten() #converts 2D => 1D
print(flattened, flattened.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)
[1 2 3 4 5 6 7 8] (8,)


In [34]:
# Indexing
arr = np.array([1, 2, 3, 4, 5]) #1D array
print(arr[0])

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) #2D array
print(arr[0][1]) #2
print(arr[1][2]) #6

#Fancy indexing
arr = np.array([1,2,3,4,5,6,7,8])
idx = [1,3,5]
print(arr[idx])

#Boolean indexing
print(arr[arr > 2]) #nums greater than 2
print(arr[arr % 2 == 0]) #even nums

1
2
6
[2 4 6]
[3 4 5 6 7 8]
[2 4 6 8]


In [35]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) #[3, 4, 5, 6]
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


In [36]:
# Copy vs View by Slicing
#Sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] #[2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy() #[2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [37]:
# Operations along Axes
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)
print(np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3]) #row(0, 1, 2) & col(1, 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [50]:
# 3D array
arr = np.array([[[2,3,4],[5,6,7]],[[11,12,13],[8,9,10]]])
print(arr)

print(arr[0,1,2])
print(arr[1,0,1])
#OR
print(arr[0][1][1])   
print(arr[1][0][0])  

print(arr[:, :, 0])        #first col from both layers
print(arr[:, 0, :])        #first row from both layers

#Manipulating data
arr[:, 0, :] = 99          #change first row to store 99
print(arr)

[[[ 2  3  4]
  [ 5  6  7]]

 [[11 12 13]
  [ 8  9 10]]]
7
12
6
11
[[ 2  5]
 [11  8]]
[[ 2  3  4]
 [11 12 13]]
[[[99 99 99]
  [ 5  6  7]]

 [[99 99 99]
  [ 8  9 10]]]


In [51]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


int32
float64
<U5
20
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [52]:
# Vectorization & Broadcasting

#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [ ]:
# Vector Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)